In [3]:
import numpy as np

In [10]:
import numpy as np

# 3.1
list = [20, 27, 9, 12, 31, 17, 4, 50, 39, 35]
arr = np.array(list)

print(arr * 4)

print(np.mean(arr))

print(np.median(arr))

print(np.std(arr))

min_idx = np.argmin(arr)
max_idx = np.argmax(arr)
print(min_idx)
print(max_idx)

print(arr[min_idx])
print(arr[max_idx])

print(np.min(arr))
print(np.max(arr))

greater_than_20 = arr[arr > 20]
print(greater_than_20)

# 3.2
matrix = [
    [5, 12, 17, 9],
    [8, 21, 14, 3],
    [6, 13, 19, 11]
]
arr_2d = np.array(matrix)

print("Shape:", arr_2d.shape)
print("Rows:", arr_2d.shape[0])
print("Columns:", arr_2d.shape[1])

print(arr_2d[:, 2])

print(arr_2d[1, :])

print(arr_2d * 2)

print(np.mean(arr_2d, axis=0))

print(np.mean(arr_2d))

print(np.max(arr_2d, axis=1))
print(np.min(arr_2d, axis=0))

flattened = arr_2d.flatten()
print(flattened)
print(flattened.shape)

flat_min_idx = np.argmin(flattened)
flat_max_idx = np.argmax(flattened)
print(flat_min_idx)
print(flat_max_idx)

min_coords = np.unravel_index(flat_min_idx, arr_2d.shape)
max_coords = np.unravel_index(flat_max_idx, arr_2d.shape)
print(min_coords)
print(max_coords)

greater_than_15 = arr_2d[arr_2d > 15]
print(greater_than_15)

sorted_arr = np.sort(arr_2d, axis=1)
print(sorted_arr)

[ 80 108  36  48 124  68  16 200 156 140]
24.4
23.5
13.828955130450023
6
7
4
50
4
50
[27 31 50 39 35]
Shape: (3, 4)
Rows: 3
Columns: 4
[17 14 19]
[ 8 21 14  3]
[[10 24 34 18]
 [16 42 28  6]
 [12 26 38 22]]
[ 6.33333333 15.33333333 16.66666667  7.66666667]
11.5
[17 21 19]
[ 5 12 14  3]
[ 5 12 17  9  8 21 14  3  6 13 19 11]
(12,)
7
5
(np.int64(1), np.int64(3))
(np.int64(1), np.int64(1))
[17 21 19]
[[ 5  9 12 17]
 [ 3  8 14 21]
 [ 6 11 13 19]]


In [5]:
def is_prime(n):
    if n < 2:
        return False
    for i in range(2, int(np.sqrt(n)) + 1):
        if n % i == 0:
            return False
    return True

def filter_prime_rows(arr):
    prime_mask = np.array([[is_prime(val) for val in row] for row in arr])
    rows_with_primes = np.any(prime_mask, axis=1)
    return arr[rows_with_primes]

arr = np.array([
    [2, 3, 5],
    [14, 6, 8],
    [11, 13, 17],
    [7, 10, 13]
])

result = filter_prime_rows(arr)
print("Rows with at least one prime:\n", result)

Rows with at least one prime:
 [[ 2  3  5]
 [11 13 17]
 [ 7 10 13]]


In [6]:
def checkerboard():
    board = np.zeros((8, 8), dtype=int)
    
    # odd-numbered rows
    for i in range(0, 8, 2):
        for j in range(0, 8, 2):
            board[i, j] = 1
    
    # even-numbered rows
    for i in range(1, 8, 2):
        for j in range(1, 8, 2):
            board[i, j] = 1
    
    return board

def reverse_checkerboard():
    board = np.ones((8, 8), dtype=int)
    
    # odd
    for i in range(0, 8, 2):
        for j in range(0, 8, 2):
            board[i, j] = 0
    
    # even
    for i in range(1, 8, 2):
        for j in range(1, 8, 2):
            board[i, j] = 0
    
    return board

print(checkerboard())
print(reverse_checkerboard())

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [9]:
def expansion(string_array, spaces):
    def expand_string(s, n):
        return (' ' * n).join(s)

    vectorized_expand = np.vectorize(expand_string)
    return vectorized_expand(string_array, spaces)

universe = np.array(['galaxy', 'clusters'])
print(expansion(universe, 1))
print(expansion(universe, 2))

['g a l a x y' 'c l u s t e r s']
['g  a  l  a  x  y' 'c  l  u  s  t  e  r  s']


In [7]:
def secondDimmest(stars):
    sorted_stars = np.sort(stars, axis=1)
    return sorted_stars[:, -2]  
    